Portfolio: Desktop version
AmanWorku/Aman-Worku-s-Portfolio pull request #10
Opened 2022-11-02 15:35 UTC by AmanWorku

- Created a desktop version of the portfolio using media query
- Added required images

2022-11-02 15:59 UTC, GiuseppeTG requested changes
Hi @AmanWorku  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif)

## Highlights

✅ Very good job with styles
✅ Responsive navbar

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 15:59 UTC, GiuseppeTG commented on index.html
>              <p>A daily selection of privately personalized reads; no accounts or sign-ups required. has been the
- [ ] Kindly check your font size on the desktop version. For example, for the desktop version, this text should be resized to 20px. The point of this is that text looks bigger when the size of the screen grows. 👍

2022-11-02 16:03 UTC, GiuseppeTG commented
- [ ] Kindly change the cursor when you hover clickable elements (buttons, links, media icons, nav-links). You can do it in the CSS using `cursor: pointer;` when an element is hovered. This improves user experience 🤓

2022-11-02 16:04 UTC, GiuseppeTG commented
- [ ] Kindly fix the link to your MIT licence in the README file, it is redirecting to a 404 page 😅

2022-11-02 16:06 UTC, GiuseppeTG commented
- [OPTIONAL] I highly suggest doing commits more often. It's good to keep good track of your work and have the option to return to previous commits if the app breaks at any point. 🤯

2022-11-02 16:11 UTC, GiuseppeTG commented
- [ ] The width of the screen for the desktop version in Figma Is 1440px.

FIGMA:
![Captura de Pantalla 2022-11-02 a la(s) 10 57 21 a  m](https://user-images.githubusercontent.com/86022690/199541111-20907062-d404-4d29-aee7-b2fb5a167945.png)

YOURS:
![Captura de Pantalla 2022-11-02 a la(s) 10 51 12 a  m](https://user-images.githubusercontent.com/86022690/199541225-667465f1-2751-439d-b745-c8211ac4bbfd.png)

Position the sections, background images, and margins keeping this issue in mind. 

There are just these minor changes, but your project is looking very good, congrats! 😄

2022-11-03 08:41 UTC, medaminedev66 requested changes
Hi @AmanWorku,
### This is a manual review
Note: It will be approved on your dashboard as soon as possible.
# Approved :+1:
Cheers and Happy coding!:clap::clap::clap:

2022-11-03 08:41 UTC, medaminedev66 commented on style.css
> +  }
[OPTIONAL] To ensure that your page is responsive as it can be, I recommend not fixing the width of the page with a specific size. It would be preferable to use `width: 100%` or `min-width` since your media query breakpoint width is 780px.

2022-11-03 08:47 UTC, merged