Portfolio: Header and Headline Section
AmanWorku/Aman-Worku-s-Portfolio pull request #2
Opened 2022-10-27 14:18 UTC by AmanWorku

- Add HTML file and inserted mandatory links
- Add CSS file to style the elements in HTML file
- Used flexbox method to design layout

2022-10-27 16:41 UTC, karlavdelgadof requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi there @AmanWorku  :smile: :wave: !

Your project page is looking fantastic so far :star_struck: ! 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses: 

![](https://media.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy.gif)

## :sparkles: Highlights :sparkles:

- The design follows the provided template :heavy_check_mark: 
- Great work using the right GitHub Flow :100: 
- Awesome file organization :card_file_box: 
- Commits are descriptive and meaningful :+1: 

Congrats on your work so far! :clap:  

## Required Changes ♻️
There are some issues that you still need to work on to go to the next project, but you are almost there! 

- [ ] For a more professionally-looking repo, I would suggest using a more descriptive name for your branches. In this way, you can ensure that anyone who accesses your code base can easily get around it and have an idea of what is being developed in that branch :bulb: :wink: . For example, in this case, you could use a name like `navbar-headline-section` or `header-section` or any other alternative you might come up with that will briefly describe the feature :+1: . 

_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me **@karlavdelgadof**  in your question so I can receive the notification.
  
  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
  
  ------
  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 16:41 UTC, karlavdelgadof commented on index.html
> +        <p>Aman Worku</p>
As part of the [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md#:~:text=HTML%20%26%20CSS%20best%20practices), I think it is important to consider using a more semantically accurate tag for your logo, in this case, you could use an `<a>` tag since it is also convenient to improve the UX :bust_in_silhouette: , by doing this you could provide the user with a direct link to your homepage by clicking the logo :100:

2022-10-27 16:41 UTC, karlavdelgadof commented on style.css
> +.container .wrapper {
As mentioned in the requirements, you must stick to the design :art: , because of this, please make sure to add the background image/illustration and the correct social icons as shown in the [Figma Template you chose](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471):

**Figma Template**
![image](https://user-images.githubusercontent.com/92395484/198347751-e946a326-2d42-4af3-8d01-d88b5186a9ee.png)


**Your Page**
![image](https://user-images.githubusercontent.com/92395484/198347981-1dcb5d9c-a108-40eb-8b11-f8caf28234eb.png)

**Tip :eyes: :** You can add the background image by implementing the [CSS property `background-image`](https://www.w3schools.com/csSref/pr_background-image.php) combined with other property like `background-size` and `background-position` :bulb:

2022-10-27 17:06 UTC, AmanWorku commented
Hi Karla,

Thank you so much for your kind words. They really mean a lot to me. But I
had this question. I can't rename the branch and even if I create a new
branch and push it, there will be a new pull request. So should I do that,
create a new branch and a new pull request?

All the best,
Aman

On Thu, Oct 27, 2022 at 7:41 PM Karla Delgado ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRED CHANGES ♻️
>
> Hi there @AmanWorku <https://github.com/AmanWorku> 😄 👋 !
>
> Your project page is looking fantastic so far 🤩 !
>
> However, I've found some room for improvement that can help you accomplish
> a more readable/clean code and make your project look professional 😎
>
>
> <https://camo.githubusercontent.com/fca3c72c3ea3a1543a08ea5032b83540eb6928d8d96efbfab3cffb0d12236796/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c7552483855475154504578326c616672442f67697068792e676966>
> ✨ Highlights ✨
>
>    - The design follows the provided template ✔️
>    - Great work using the right GitHub Flow 💯
>    - Awesome file organization 🗃️
>    - Commits are descriptive and meaningful 👍
>
> Congrats on your work so far! 👏
> Required Changes ♻️
>
> There are some issues that you still need to work on to go to the next
> project, but you are almost there!
>
>    - For a more professionally-looking repo, I would suggest using a more
>    descriptive name for your branches. In this way, you can ensure that anyone
>    who accesses your code base can easily get around it and have an idea of
>    what is being developed in that branch 💡 😉 . For example, in this
>    case, you could use a name like navbar-headline-section or
>    header-section or any other alternative you might come up with that
>    will briefly describe the feature 👍 .
>
> *For more information, check the comments under the review ⬇️*
> Optional suggestions ☑️
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can improve the quality of your code 💯*
>
> Happy coding and keep it up! 🙌
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Remember to tag me ***@***.*** <https://github.com/karlavdelgadof>*
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/AmanWorku/Aman-Worku-s-Portfolio/pull/2#discussion_r1007116451>
> :
>
> > +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <link rel="stylesheet" type="text/css" href="style.css">
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +    <link href="https://fonts.googleapis.com/css2?family=Crete+Round&family=Poppins&family=Roboto&display=swap" rel="stylesheet">
>
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">
>
> +    <title>Aman Worku's Portfolio</title>
>
> +</head>
>
> +<body>
>
> +    <header class="toolbar">
>
> +        <p>Aman Worku</p>
>
>
> As part of the HTML & CSS best practices
> <https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md#:~:text=HTML%20%26%20CSS%20best%20practices>,
> I think it is important to consider using a more semantically accurate tag
> for your logo, in this case, you could use an <a> tag since it is also
> convenient to improve the UX 👤 , by doing this you could provide the
> user with a direct link to your homepage by clicking the logo 💯
> ------------------------------
>
> In style.css
> <https://github.com/AmanWorku/Aman-Worku-s-Portfolio/pull/2#discussion_r1007127010>
> :
>
> > +  flex-grow: none;
>
> +  flex-direction: row;
>
> +  align-items: flex-start;
>
> +  justify-content: space-between;
>
> +  border-radius: 8px;
>
> +}
>
> +
>
> +.container > * {
>
> +  box-sizing: border-box;
>
> +}
>
> +
>
> +.container {
>
> +  background: #1c1a19;
>
> +}
>
> +
>
> +.container .wrapper {
>
>
> As mentioned in the requirements, you must stick to the design 🎨 ,
> because of this, please make sure to add the background image/illustration
> and the correct social icons as shown in the Figma Template you chose
> <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471>
> :
>
> *Figma Template*
> [image: image]
> <https://user-images.githubusercontent.com/92395484/198347751-e946a326-2d42-4af3-8d01-d88b5186a9ee.png>
>
> *Your Page*
> [image: image]
> <https://user-images.githubusercontent.com/92395484/198347981-1dcb5d9c-a108-40eb-8b11-f8caf28234eb.png>
>
> *Tip 👀 :* You can add the background image by implementing the CSS
> property background-image
> <https://www.w3schools.com/csSref/pr_background-image.php> combined with
> other property like background-size and background-position 💡
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AmanWorku/Aman-Worku-s-Portfolio/pull/2#pullrequestreview-1158634753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATDCLQYQRA5GL7237G4MA3TWFKWDVANCNFSM6AAAAAARQDSYXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-27 20:26 UTC, merged

2024-08-15 15:36 UTC, karlaAleciram9020 reviewed
Muy bien